CollegeERP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('info.urls')),
    path('info/', include('info.urls')),
    path('accounts/login/',
         auth_views.LoginView.as_view(template_name='info/login.html'), name='login'),
    path('accounts/logout/',
         auth_views.LogoutView.as_view(template_name='info/logout.html'), name='logout'),
]

info/urls.py
from django.urls import path
from . import views
from django.contrib import admin


urlpatterns = [
    path('', views.index, name='fciscu'),
    path('studentservices/', views.studentservices, name='studentservices'),
    path('about/', views.about, name='about'),
    path('studyatfci/', views.studyatfci, name='studyatfci'),
    path('studentactivity/', views.studentactivity, name='studentactivity'),
    path('activity_sport/', views.activity_sport, name='activity_sport'),
    path('cultural_activity/', views.cultural_activity, name='cultural_activity'),
    path('grade_four_is_exam_result/', views.grade_four_is_exam_result,
         name='grade_four_is_exam_result'),
    path('grade_four_is_exam_schedule/', views.grade_four_is_exam_schedule,
         name='grade_four_is_exam_schedule'),
    path('lecture_shedule/', views.lecture_shedule, name='lecture_shedule'),
    path('news_and_events/', views.news_and_events, name='news_and_events'),
    path('faculty_services/', views.student_additional_services,
         name='student_additional_services'),
    path('vision_and_mission/', views.vision_and_mission,
         name='vision_and_mission'),
    path('artistic_activity/', views.artistic_activity, name='artistic_activity'),
    path('student/<slug:stud_id>/attendance/',
         views.attendance, name='attendance'),
    path('student/<slug:stud_id>/<slug:course_id>/attendance/',
         views.attendance_detail, name='attendance_detail'),
    path('student/<slug:class_id>/timetable/',
         views.timetable, name='timetable'),
    # path('student/<slug:class_id>/search/', views.student_search, name='student_search'),

    path('student/<slug:stud_id>/marks_list/',
         views.marks_list, name='marks_list'),

    path('teacher/<slug:teacher_id>/<int:choice>/Classes/',
         views.t_clas, name='t_clas'),
    path('teacher/<int:assign_id>/Students/attendance/',
         views.t_student, name='t_student'),
    path('teacher/<int:assign_id>/ClassDates/',
         views.t_class_date, name='t_class_date'),
    path('teacher/<int:ass_c_id>/Cancel/',
         views.cancel_class, name='cancel_class'),
    path('teacher/<int:ass_c_id>/attendance/',
         views.t_attendance, name='t_attendance'),
    path('teacher/<int:ass_c_id>/Edit_att/', views.edit_att, name='edit_att'),
    path('teacher/<int:ass_c_id>/attendance/confirm/',
         views.confirm, name='confirm'),
    path('teacher/<slug:stud_id>/<slug:course_id>/attendance/',
         views.t_attendance_detail, name='t_attendance_detail'),
    path('teacher/<int:att_id>/change_attendance/',
         views.change_att, name='change_att'),
    path('teacher/<int:assign_id>/Extra_class/',
         views.t_extra_class, name='t_extra_class'),
    path('teacher/<slug:assign_id>/Extra_class/confirm/',
         views.e_confirm, name='e_confirm'),
    path('teacher/<int:assign_id>/Report/', views.t_report, name='t_report'),

    path('teacher/<slug:teacher_id>/t_timetable/',
         views.t_timetable, name='t_timetable'),
    path('teacher/<int:asst_id>/Free_teachers/',
         views.free_teachers, name='free_teachers'),

    path('teacher/<int:assign_id>/marks_list/',
         views.t_marks_list, name='t_marks_list'),
    path('teacher/<int:assign_id>/Students/Marks/',
         views.student_marks, name='t_student_marks'),
    path('teacher/<int:marks_c_id>/marks_entry/',
         views.t_marks_entry, name='t_marks_entry'),
    path('teacher/<int:marks_c_id>/marks_entry/confirm/',
         views.marks_confirm, name='marks_confirm'),
    path('teacher/<int:marks_c_id>/Edit_marks/',
         views.edit_marks, name='edit_marks'),

]
admin.site.site_url = None
admin.site.site_header = 'FCI SCU Administration'

info/models.py
from django.db import models
import math
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save, post_delete
from datetime import timedelta

# Create your models here.
sex_choice = (
    ('Male', 'Male'),
    ('Female', 'Female')
)

time_slots = (
    ('7:30 - 8:30', '7:30 - 8:30'),
    ('8:30 - 9:30', '8:30 - 9:30'),
    ('9:30 - 10:30', '9:30 - 10:30'),
    ('11:00 - 11:50', '11:00 - 11:50'),
    ('11:50 - 12:40', '11:50 - 12:40'),
    ('12:40 - 1:30', '12:40 - 1:30'),
    ('2:30 - 3:30', '2:30 - 3:30'),
    ('3:30 - 4:30', '3:30 - 4:30'),
    ('4:30 - 5:30', '4:30 - 5:30'),
)

DAYS_OF_WEEK = (
    ('Sunday', 'Sunday'),
    ('Monday', 'Monday'),
    ('Tuesday', 'Tuesday'),
    ('Wednesday', 'Wednesday'),
    ('Thursday', 'Thursday'),
)

test_name = (
    ('Quiz 1', 'Quiz 1'),
    ('Quiz 2', 'Quiz 2'),
    ('Quiz 3', 'Quiz 3'),
    ('MidTerm 1', 'MidTerm 1'),
    ('MidTerm 2', 'MidTerm 2'),
    ('Semester End Exam', 'Semester End Exam'),
)

final_results = (
    ('ضعيف', 'ضعيف'),
    ('مقبول', 'مقبول'),
    ('جيد', 'جيد'),
    ('جيد جدا', 'جيد جدا'),
    ('امتياز', 'امتياز')
)


class User(AbstractUser):
    @property
    def is_student(self):
        if hasattr(self, 'student'):
            return True
        return False

    @property
    def is_teacher(self):
        if hasattr(self, 'teacher'):
            return True
        return False


class Dept(models.Model):
    id = models.CharField(primary_key='True', max_length=100)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Course(models.Model):
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE)
    id = models.CharField(primary_key='True', max_length=50)
    name = models.CharField(max_length=50)
    shortname = models.CharField(max_length=50, default='X')

    def __str__(self):
        return self.name


class Class(models.Model):
    # courses = models.ManyToManyField(Course, default=1)
    id = models.CharField(primary_key='True', max_length=100)
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE)
    section = models.CharField(max_length=100)
    level = models.IntegerField()

    class Meta:
        verbose_name_plural = 'classes'

    def __str__(self):
        d = Dept.objects.get(name=self.dept)
        return '%s : %d %s' % (d.name, self.level, self.section)


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    class_id = models.ForeignKey(Class, on_delete=models.CASCADE, default=1)
    USN = models.CharField(primary_key='True', max_length=100)
    name = models.CharField(max_length=200)
    sex = models.CharField(max_length=50, choices=sex_choice, default='Male')
    DOB = models.DateField(default='1998-01-01')

    def __str__(self):
        return self.name


class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    id = models.CharField(primary_key=True, max_length=100)
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=100)
    sex = models.CharField(max_length=50, choices=sex_choice, default='Male')
    DOB = models.DateField(default='1980-01-01')

    def __str__(self):
        return self.name


class Assign(models.Model):
    class_id = models.ForeignKey(Class, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('course', 'class_id', 'teacher'),)

    def __str__(self):
        cl = Class.objects.get(id=self.class_id_id)
        cr = Course.objects.get(id=self.course_id)
        te = Teacher.objects.get(id=self.teacher_id)
        return '%s : %s : %s' % (te.name, cr.shortname, cl)


class AssignTime(models.Model):
    assign = models.ForeignKey(Assign, on_delete=models.CASCADE)
    period = models.CharField(
        max_length=50, choices=time_slots, default='11:00 - 11:50')
    day = models.CharField(max_length=15, choices=DAYS_OF_WEEK)


class AttendanceClass(models.Model):
    assign = models.ForeignKey(Assign, on_delete=models.CASCADE)
    date = models.DateField()
    status = models.IntegerField(default=0)

    class Meta:
        verbose_name = 'Attendance'
        verbose_name_plural = 'Attendance'


class Attendance(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    attendanceclass = models.ForeignKey(
        AttendanceClass, on_delete=models.CASCADE, default=1)
    date = models.DateField(default='2018-10-23')
    status = models.BooleanField(default='True')

    def __str__(self):
        sname = Student.objects.get(name=self.student)
        cname = Course.objects.get(name=self.course)
        return '%s : %s' % (sname.name, cname.shortname)


class AttendanceTotal(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('student', 'course'),)

    @property
    def att_class(self):
        stud = Student.objects.get(name=self.student)
        cr = Course.objects.get(name=self.course)
        att_class = Attendance.objects.filter(
            course=cr, student=stud, status='True').count()
        return att_class

    @property
    def total_class(self):
        stud = Student.objects.get(name=self.student)
        cr = Course.objects.get(name=self.course)
        total_class = Attendance.objects.filter(
            course=cr, student=stud).count()
        return total_class

    @property
    def attendance(self):
        stud = Student.objects.get(name=self.student)
        cr = Course.objects.get(name=self.course)
        total_class = Attendance.objects.filter(
            course=cr, student=stud).count()
        att_class = Attendance.objects.filter(
            course=cr, student=stud, status='True').count()
        if total_class == 0:
            attendance = 0
        else:
            attendance = round(att_class / total_class * 100, 2)
        return attendance

    @property
    def classes_to_attend(self):
        stud = Student.objects.get(name=self.student)
        cr = Course.objects.get(name=self.course)
        total_class = Attendance.objects.filter(
            course=cr, student=stud).count()
        att_class = Attendance.objects.filter(
            course=cr, student=stud, status='True').count()
        cta = math.ceil((0.75 * total_class - att_class) / 0.25)
        if cta < 0:
            return 0
        return cta


class StudentCourse(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('student', 'course'),)
        verbose_name_plural = 'Marks'

    def __str__(self):
        sname = Student.objects.get(name=self.student)
        cname = Course.objects.get(name=self.course)
        return '%s : %s' % (sname.name, cname.shortname)

    def get_cie(self):
        marks_list = self.marks_set.all()
        m = []
        for mk in marks_list:
            m.append(mk.marks1)
        cie = math.ceil(sum(m[:5]) / 2)
        return cie

    def get_attendance(self):
        a = AttendanceTotal.objects.get(
            student=self.student, course=self.course)
        return a.attendance


class Marks(models.Model):
    studentcourse = models.ForeignKey(StudentCourse, on_delete=models.CASCADE)
    name = models.CharField(
        max_length=50, choices=test_name, default='Quiz 1')
    marks1 = models.IntegerField(default=0, validators=[
                                 MinValueValidator(0), MaxValueValidator(100)])

    class Meta:
        unique_together = (('studentcourse', 'name'),)

    @property
    def total_marks(self):
        if self.name == 'Semester End Exam':
            return 100
        return 20


class MarksClass(models.Model):
    assign = models.ForeignKey(Assign, on_delete=models.CASCADE)
    name = models.CharField(
        max_length=50, choices=test_name, default='Quiz 1')
    status = models.BooleanField(default='False')

    class Meta:
        unique_together = (('assign', 'name'),)

    @property
    def total_marks(self):
        if self.name == 'Semester End Exam':
            return 100
        return 20


class AttendanceRange(models.Model):
    start_date = models.DateField()
    end_date = models.DateField()


class FinalResult(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    results = models.CharField(
        max_length=7, choices=final_results, default='امتياز')

    class Meta:
        unique_together = (('student', 'course'),)

    def __str__(self):
        sname = Student.objects.get(name=self.student)
        cname = Course.objects.get(name=self.course)
        return '%s : %s' % (sname.name, cname.name)
# Triggers


def daterange(start_date, end_date):
    for n in range(int((end_date - start_date).days)):
        yield start_date + timedelta(n)


days = {
    'Sunday': 1,
    'Monday': 2,
    'Tuesday': 3,
    'Wednesday': 4,
    'Thursday': 5,
}


def create_attendance(sender, instance, **kwargs):
    if kwargs['created']:
        start_date = AttendanceRange.objects.all()[:1].get().start_date
        end_date = AttendanceRange.objects.all()[:1].get().end_date
        for single_date in daterange(start_date, end_date):
            if single_date.isoweekday() == days[instance.day]:
                try:
                    AttendanceClass.objects.get(date=single_date.strftime(
                        "%Y-%m-%d"), assign=instance.assign)
                except AttendanceClass.DoesNotExist:

info/templates/info/ArtisticActivity.html
<!DOCTYPE html>
<html>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>كلية الحاسبات و المعلومات</title>
    {% load static %}

    <link rel="shortcut icon" href="images/fci-logo.ico">
    <meta name="Description" <!--Main Element CSS-->
    <link href="{% static '/info/homepage/css/style.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static '/info/homepage/css/form.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static '/info/homepage/css/font-awesome.css' %}" rel="stylesheet" type="text/css">

    <!--Flexy Menu CSS-->
    <link href="{% static '/info/homepage/css/flexy-menu.css' %}" rel="stylesheet" type="text/css">
    <!--LayerSlider CSS-->
    <link href="../layerslider/css/layerslider.css' %}" rel="stylesheet" type="text/css">
    <!--Important Owl CSS-->
    <link href="{% static '/info/homepage/css/owl.carousel.css' %}" rel="stylesheet" type="text/css">
    <!--Owl DefaultTheme -->
    <link href="{% static '/info/homepage/css/owl.theme.css' %}" rel="stylesheet" type="text/css">

    <link href="{% static '/info/homepage/css/slideshow.css' %}" rel="stylesheet" />

    <link rel="stylesheet" href="../css/2-second-layout-color-5.css' %}">
    <link rel="stylesheet" type="text/css" href="../css/jquery.simplyscroll.css' %}" media="screen" />

</head>

<body class="d-block w-100" alt="slideShow">
    <style type="text/css">
        body {
            background: linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
            background-size: 400% 400%;
            animation: gradient 30s ease infinite;
        }

        @keyframes gradient {
            0% {
                background-position: 0% 50%;
            }

            50% {
                background-position: 100% 50%;
            }

            100% {
                background-position: 0% 50%;
            }
        }
    </style>

   

    <div class="wrapper" >
        <header class="header-section">
            <div class="logo">
                <div class="logo-wrapper">
                    <a href="{% url 'fciscu' %}"><img src="{% static 'info/images/fci-logo.jpg' %}"
                            style="width: 200px; mix-blend-mode: multiply; padding-right: 25px;padding-top: 40px;" /></a>
                </div>
            </div>

            <ul class="flexy-menu">
                <li id="home">
                    <a href="{% url 'fciscu' %}"> <i class="fa fa-home"></i> Home</a>

                </li>

                <li id="number">
                    <a href="{% url 'about' %}"><i class="fa fa-thumbs-o-up"></i> About</a>
                    <div class="menu-space"></div>

                </li>
                <li id="contact"><a href="{% url 'studyatfci' %}"><i class="fa fa-users"></i> Study At FCI</a>
                    <div class="menu-space"></div>
                </li>
                <li id="about"><a href="{% url 'news_and_events' %}"><i class="fa fa-lightbulb-o"></i> News & Events</a>
                    <div class="menu-space"></div>
                </li>
                <li id="contact"> <a href="{% url 'student_additional_services' %}"><i class="fa fa-envelope-o"></i>
                        Student
                        Services</a>
                    <div class="menu-space"></div>
                </li>
               
            </ul>

        </header>
       
        <div class="container" style="padding-top: 40px;">
            <div class="content-wrapper">
                <section class="stripe service-panel">
                    <nav className="navbar navbar-light bg-light">
                        <div className="container-fluid">
                            <h2 style="text-align: center;">النشاط الفني</h2>
                        </div>
                    </nav>
                    <br />


                    <h3>الفنون التشكيلية</h3>
                    <br />
                    <p>التصوير الزيتي و الرسم</p>
                    <p>الرسم بالرصاص</p>
                    <p>النحت و الخزف</p>
                    <p>التصميم - اعلان - زخرفة - خط عربي</p>
                    <p>الأشغال الفنية - أشغال جلود - معادن - أشغال النجارة - تصوير ضوئي </p>

                    <br />
                    <br />
                    <hr>
                    <br>
                    <br>
                    <h3>شروط التسابق</h3>
                    <br />
                    <p>أن تكون الأعمال المقدمة من انتاج الطالب</p>
                    <p>تقدم كل عدد 25 عملا فنيا</p>
                    <p>يخصص لكل جامعة مساحة داخل المعرض تقوم بتنسيق الأعمال بها</p>
                    <p>يشارك عدد 2 طالب أو طالبة + مشرف بالمعرض</p>

                    <br />
                    <br />
                    <hr>
                    <br>
                    <br>
                    <h3>الفنون الشعبية</h3>
                    <br />
                    <p>تقديم عدد ثلاثة أعمال من ابداعات البيئة الشعبية</th>
                    <p>مدة العرض لا تزيد عن 30 دقيقة</th>
                    <p>الاستعانة بالموسيقى المسجلة</th>
                    <p>تشارك الجامعة بعدد 15 طالب و طالبة + مشرف</th>
                        <br />
                        <br />
                        <br />
                        <hr>
                        <br>
                        <br>
                    <h3>الموسيقى و الكورال</h3>
                    <br />
                    <p>عزف فردي</p>
                    <p>الغناء الفردي و الجماعي</p>
                    <p>يتكون الفريق من 15 طالب و طالبة + مشرف</p>
                    <p>الزمن المحدد للتسابق 45 دقيقة</p>

                    <br />
                    <br />
                    <br />

                    <div class="footer-bottom">
                        <div class="copyright">
                            Copyright © 2021 <a target="_blank">FCI</a>
                        </div>

                    </div>

            </div>


            <!--Go To Top-->
            <a href="#" class="back-to-top"></a>
            <!--End-->

            </footer>
            <!--Footer End-->

        </div>

    </div>

    <div class="clearfix"></div>


    <script type="text/javascript" src="{% static '/info/homepage/js/jquery-1.10.2.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/info/homepage/js/greensock.js' %}"></script>
    <!--Flexy Menu Script-->
    <script type="text/javascript" src="{% static '/info/homepage/js/flexy-menu.js' %}"></script>
    <!--LayerSlider Script-->
    <script type="text/javascript" src="../layerslider/js/layerslider.kreaturamedia.jquery.js' "></script>
    <script type="text/javascript" src="../layerslider/js/layerslider.transitions.js' "></script>
    <!--Carousel Plugin Script-->
    <script type="text/javascript" src="{% static '/info/homepage/js/owl.carousel.js' %}"></script>
    <!-- MEGAFOLIO PRO GALLERY SCRIPT -->
    <script type="text/javascript" src="megafolio/js/jquery.themepunch.megafoliopro.js' "></script>
    <!-- COLORBOX LIGHTBOX SCRIPT -->
    <script type="text/javascript" src="{% static '/info/homepage/js/jquery.colorbox.js' %}"></script>
    <!--Social Share Button Script-->
    <script src="{% static '/info/homepage/js/jquery.sharrre.min.js' %}" type="text/javascript"></script>
    <!-- Fancybox Script -->
    <script type="text/javascript" src="{% static '/info/homepage/js/jquery.fancybox.pack8cbb8cbb.js?v=2.1.5"></script>
    <!--Tooltip Script-->
    <script type="text/javascript" src="{% static '/info/homepage/js/tooltip.js' %}"></script>
    <!--Placeholder Script-->
    <script type="text/javascript" src="{% static '/info/homepage/js/placeholder.js' %}"></script>
    <!--model Script-->
    <script type="text/javascript" src="{% static '/info/homepage/js/jquery.modal.min.js' %}"></script>
    <!--Custom-->
    <script type="text/javascript" src="{% static '/info/homepage/js/custom.js' %}"></script>



    <script src="{% static '/info/homepage/js/slideshow.js' %}"></script>


</body>

<!-- Mirrored from elshennawy.com/ by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 19 Dec 2021 12:28:06 GMT -->

</html>

info/templates/info/att_detail.html
{% extends 'info/base.html' %}

    {% block content %}
        <div class="card mb-3">
            <div class="card-header">
              <i class="fas fa-table"></i>
            <strong>{{ cr.name }}</strong></div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                        <th>#</th>
                        <th>Date</th>
                        <th>Day</th>
                        <th>Status</th>
                        <th></th>
                    </tr>
                  </thead>
                  <tbody>
                        {% for a in att_list %}
                        <tr class="row100 body">
                            <td>{{ forloop.counter }}</td>
                            <td>{{ a.date }}</td>
                            <td>{{ a.date|date:"l" }}</td>
                            {% if a.status %}
                            <td class="p-3 mb-2 bg-success text-white">Present <span class="glyphicon glyphicon-thumbs-up"></span></td>
                            {% else %}
                            <td class="p-3 mb-2 bg-danger text-white">Absent <span class="glyphicon glyphicon-thumbs-down"></span</td>
                            {% endif %}
                        </tr>
                    {% empty %}
                            <p>student has no attendance</p>
                    {% endfor %}

                  </tbody>
                </table>
              </div>
            </div>
          </div>


    {% endblock %}

info/templates/info/attendance.html
{% extends 'info/base.html' %}
    {% load static %}

    {% block content %}
                  <div class="card mb-3">
            <div class="card-header">
              <i class="fas fa-table"></i>
            <b>Attendance</b></div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered text-center" id="dataTable" width="100%" cellspacing="0">
                  <thead class="thead-light ">
                    <tr>
                        <th>Course ID</th>
                        <th>Course name</th>
                        <th>Attended classes</th>
                        <th>Total classes</th>
                        <th>Attendance %</th>
                        <th>Classes to attend</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for a in att_list %}
                    <tr>
                        <td>{{ a.course_id }}</td>
                        <td><a href="{% url 'attendance_detail' a.student.USN a.course.id %}">{{a.course.name}}</a></td>
                        <td>{{ a.att_class }}</td>
                        <td>{{ a.total_class }}</td>
                        {% if a.attendance < 75 %}
                            <td class="p-3 mb-2 bg-danger text-white">{{ a.attendance }}</td>
                        {% else %}
                            <td class="p-3 mb-2 bg-success text-white">{{ a.attendance }}</td>
                        {% endif %}
                        <td>{{ a.classes_to_attend }}</td>
                    </tr>
                    {% empty %}
                            <p>student has no courses</p>
                    {% endfor %}

                  </tbody>
                </table>
              </div>
            </div>
          </div>


    {% endblock %}

info/templates/info/free_teachers.html
{% load static %}

<!-- Bootstrap core CSS-->
<link href="{% static '/info/bootstrap/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

<!-- Custom fonts for this template-->
<link href="{% static '/info/bootstrap/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <h2 class="text-center">List Of Free Teachers</h2>
    <ul class="list-group">
        {% for t in ft_list %}
            <li class="list-group-item list-group-item-success">{{ t }}</li>
        {% endfor %}
    </ul>

info/templates/info/t_attendance.html
{% extends 'info/base.html' %}
{% block content %}
{% if c.student_set.all %}

<form action="{% url 'confirm' assc.id %}" method="post">
            {% csrf_token %}
    <div class="card mb-3">
        <div class="card-header">
          <i class="fas fa-table"></i>
         <b>{{ dept1.name }}</b></div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                    <th>Student name</th>
                    <th></th>
                </tr>
              </thead>
                <tbody>
                {% for s in c.student_set.all %}
                    <tr>
                    <td>{{s.name}}</td>
                    <td>
                        <div class="btn-group btn-group-toggle" data-toggle="buttons">

                                <label class="btn btn-outline-success active">
                                    <input type="radio" name="{{ s.USN }}" id="option1" autocomplete="off" value="present" checked> Present
                                </label>

                                <label class="btn btn-outline-danger">
                                    <input type="radio" name="{{ s.USN }}" id="option2" autocomplete="off" value="absent"> Absent
                                </label>
                        </div>
                    </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
          </div>
        </div>
      </div>


    <input class="btn btn-success" type="submit" value="Submit">
</form>


{% else %}
    <p>No students in Class</p>
{% endif %}

{% endblock %}